name: build

on:
  push:
    branches: [ "*.x" ]
  pull_request:
    branches: [ "*.x" ]

env:
  fail-fast: true

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          
    steps:
    - uses: actions/checkout@v2

    - name: "Install PHP"
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: xdebug

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}

    - name: Install dependencies
      run: composer update --prefer-dist --no-progress

    - name: Run test suite
      run: vendor/bin/phpunit

    - name: Publish to coveralls.io
      uses: coverallsapp/github-action@v1.1.2
      with:
        github-token: ${{ github.token }}

    - name: Run coding style check
      run: vendor/bin/phpcs --standard=PSR1 src/
